# General Simulation Settings
simulation:
  file_name: "game_1B.csv"       # File name for saving simulation results
  folder_name: "game_1B"           # Folder name for saving logs and outputs
  has_bridge: true                         # Whether the bridge exists in the network
  num_rounds: 40                            # Number of rounds in the simulation
  num_agents: 18                           # Number of agents participating

# History Representation
history_representation:
  prompting_style:                         # Style of prompting
    type: "consecutive"                    # Options: "consecutive", "zero-shot"

  choice_representation:                   # How choices are represented
    everyone_choices:                      
      include: true                        
      type: "aggregate"                    # Options: "individual", "aggregate"
      rounds: "per-round"                  # Options: "per-round", "aggregate" (only relevant for zero-shot)
    my_choice:                             
      include: true                        
      rounds: "per-round"                   # Options: "per-round", "aggregate" (only relevant for zero-shot)

  payoff_representation:                   # How payoff is represented
    everyone_payoff:                       
      include: false                        
      type: "aggregate"                    # Options: "individual", "aggregate"
      rounds: "averaged"                   # Options: "per-round", "averaged" (only relevant for zero-shot)
    my_payoff:                             
      include: true                       
      rounds: "per-round"                  # Options: "per-round", "averaged" (only relevant for zero-shot)

  regret_representation:                   # How regret is represented
    everyone_regret:                       
      include: false                        
      type: "individual"                   # Options: "individual", "aggregate"
      rounds: "per-round"                  # Options: "per-round", "averaged" (only relevant for zero-shot)
    my_regret:                             
      include: false                       
      rounds: "averaged"                   # Options: "per-round", "averaged" (only relevant for zero-shot)